name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log into registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u fwilhe --password-stdin

    - name: push
      run: |
        docker build --file Containerfile .

    - name: push
      run: |
        docker push fwilhe/dev

